### ISSUE TITLE
Redesign Admin Login UI

### ISSUE THREAD

**Issue by aswinshenoy** [amfoss/qpg#9]
Redesign default admin login UI.

A example of this is implemented in `amfoss/cms` and can be viewed at [api.amfoss.in/admin](https://api.amfoss.in/admin).
![image](https://user-images.githubusercontent.com/21276922/59983617-8e899c80-963f-11e9-8bdf-bdf50d4bdf9d.png)

**Comment by amreshk005** [comment]
@aswinshenoy can I work on this.

**Comment by aswinshenoy** [comment]
sure :) Go ahead.

**Comment by vibhoothi** [comment]
@amreshk005 I have assigned you the issue.

**Comment by harshithpabbati** [comment]
Closing this issue. It's already solved by @amreshk005
